customhost = "employee.cr2y4u6qgu39.us-east-1.rds.amazonaws.com"
customuser = "gurpreet"
custompass = "employee123"
customdb = "employee"
custombucket = "addbucket29"
customregion = "us-east-1"
